name: webixes
description: This is the flutter mobile application for citydeal cms

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.1+3

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  http: ^0.13.4
  provider: ^5.0.0
  json_annotation: ^4.6.0
  logging: ^1.0.2
  connectivity: ^3.0.6
  shimmer: ^2.0.0
  bordered_text: ^2.0.0
  flutter_html: ^3.0.0-alpha.5
  flutter_svg: ^1.1.1+1
  url_launcher: ^6.1.5
  toast: ^0.3.0
  shared_preferences: ^2.0.15
 # flutter_icons: ^1.1.0
  dotted_line: ^3.1.0
  timeline_list: ^0.0.6
 # progress_dialog: ^1.2.4
  #after_init: ^0.1.2
  webview_flutter: ^3.0.4
  clipboard: ^0.1.3
  google_fonts: ^3.0.1
  flutter_rating_bar: ^4.0.1
  expandable: ^5.0.1
  dropdown_search: ^5.0.2
  flutter_countdown_timer: ^4.1.0
  #splashscreen: ^1.3.5
  package_info: ^2.0.2
  intl_phone_number_input: ^0.7.0+2
  flutter_chat_bubble: ^2.0.0
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.5
  carousel_slider: ^4.1.1
  cached_network_image: ^3.2.1
  timeline_tile: ^2.0.0
  shared_value: ^3.0.0
  rename: ^2.0.1
  permission_handler: ^6.1.3
  scan: ^1.6.0

  #permission_handler: ^6.1.3

  image_picker: ^0.8.5+3
  flutter_facebook_auth: ^4.4.0+1
  google_sign_in: ^5.4.0
  google_maps_place_picker: ^2.1.0-nullsafety.3
  firebase_messaging: ^12.0.0
  one_context: ^2.0.0
  social_share: ^2.2.1
  flutter_typeahead: ^4.0.0
  photo_view: ^0.14.0
  intl: ^0.17.0
  qr_code_scanner: ^1.0.0
  location: ^4.4.0
 # smooth_star_rating: ^1.1.1
  geocode: ^1.0.1
  file_picker: ^3.0.4
  share_plus: ^4.0.10
  firebase_dynamic_links: ^4.3.2
  onboarding_overlay: ^3.1.0
dependency_overrides:
  firebase_messaging_platform_interface: 3.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.2.0
  json_serializable: ^6.3.1
  flutter_launcher_icons: ^0.9.3
  google_maps_flutter: ^2.1.8
  change_app_package_name: ^1.1.0





flutter_icons:
  android: true
  ios: true
  image_path: "assets/app_logo.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
    - dummy_assets/
    - citydeal/img/
    - citydeal/img/core-img/
    - citydeal/img/icons/
    - citydeal/img/bg-img/
    - citydeal/img/product/
    - citydeal/img/demo-img/hariOmShopImg.jpg
    - assets/call.png
    - assets/thumb_like.png





  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
